---
- name: Check all nodes are in schedulable state
  k8s_info:
    kind: Node
    field_selectors:
      - spec.unschedulable=true
  register: nodes
  retries: 300
  delay: 10
  until:
    - "'resources' in nodes"
    - "nodes.resources|length >= 3"
- name: Pause for while to ensure that all nodes are available
- pause:
    seconds: 10
- name: Check all nodes are in schedulable state - round 2
  k8s_info:
    kind: Node
    field_selectors:
      - spec.unschedulable=true
  register: nodes
  retries: 100
  delay: 30
  until:
    - "'resources' in nodes"
    - "nodes.resources|length >= 3"
